name: lct25-7
services:
  back:
    container_name: back
    build:
      dockerfile: ./Dockerfile
      context: ./back
    env_file: .env
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./back/src:/app
      - ./back/data:/app/data
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload