api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http2:
      maxConcurrentStreams: 250
    http:
      tls: {}
    transport:
      respondingTimeouts:
        readTimeout: "120s"
        writeTimeout: "120s"
        idleTimeout: "180s"

certificatesResolvers:
  myresolver:
    acme:
      email: opexu1986@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    network: lct25-7

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: "DEBUG"
